### ISSUE TITLE
Set user agent header with sdk version 

### ISSUE THREAD

**Issue by toymachiner62** [catalyticlabs/catalytic-sdk-php#11]
In order to track what version of the sdk is calling which endpoints, we need to send a user-agent string from the sdk to the underlying rest api.

This will allow us to identify in the logs, which version of an sdk is hitting specific endpoints. This will be useful when wanting to remove endpoints from pushbot-api because we can know which versions of an sdk need to be deprecated prior.

**Comment by dylanlingelbach** [comment]
@toymachiner62 I think we can close this?

**Comment by toymachiner62** [comment]
No I want to make it more dynamic. Currently you have to update it manually when releasing.
